# Site settings
title: Look, it's Cook
email: matt@lookitscook.com
description: ""
baseurl: ""
url: "https://www.lookitscook.com"
twitter_username: lookitscook
github_username: matt-cook

# Build settings
markdown: kramdown
